### ISSUE TITLE
Rule 45 cannot be parsed in Python

### ISSUE THREAD

**Issue by mogoman** [PHPIDS/PHPIDS#18] opened 2012-10-15 14:55 UTC
Rule 45 can't be parsed - I spent a bit of time on the expression, but can't nail down the problem.

```
<filter>
    <id>45</id>
    <rule><![CDATA[(?:union\s*(?:all|distinct|[(!@]*)?\s*[([]*\s*select)|(?:\w\s+like\s+\")|(?:like\s*"\%)|(?:"\s*like\W*["\d])|(?:"\s*(?:n?and|x?or|not |\|\||\&\&)\s+[\s\w]+=\s*\w+\s*having)|(?:"\s*\*\s*\w+\W+")|(?:"\s*[^?\w\s=.,;)(]+\s*[(@"]*\s*\w+\W+\w)|(?:select\s*[\[\]()\s\w\.,"-]+from)|(?:find_in_set\s*\()]]></rule>
    <description>Detects basic SQL authentication bypass attempts 2/3</description>
    <tags>
        <tag>sqli</tag>
        <tag>id</tag>
        <tag>lfi</tag>
    </tags>
    <impact>7</impact>
</filter>
```

**Comment by lstrojny** [comment] 2012-10-15 15:14
Thanks for the bug report. As I'm not too familiar with Python, what was the example function call that failed?

**Comment by mogoman** [comment] 2012-10-16 08:05
Here is a short test script (copy to test.py and run with "python test.py")

```
import re

rule = '(?:union\s*(?:all|distinct|[(!@]*)?\s*[([]*\s*select)|(?:\w\s+like\s+\")|(?:like\s*"\%)|(?:"\s*like\W*["\d])|(?:"\s*(?:n?and|x?or|not |\|\||\&\&)\s+[\s\w]+=\s*\w+\s*having)|(?:"\s*\*\s*\w+\W+")|(?:"\s*[^?\w\s=.,;)(]+\s*[(@"]*\s*\w+\W+\w)|(?:select\s*[\[\]()\s\w\.,"-]+from)|(?:find_in_set\s*\()'

try:
    compiled = re.compile(rule)
except Exception:
    print "The rule '%s' cannot be compiled properly" % rule
```

**Comment by felixbuenemann** [comment] 2013-03-26 19:02
The problem is that there is a logic error in the first part of the regex: `(?:union\s*(?:all|distinct|[(!@]*)?\s*[([]*\s*select)`

In particular the subpart: `(?:all|distinct|[(!@]*)?`

As you can see it can match _all_, _distinct_, or (simplified) nothing. But after the parentheses it requires at least one match. How are you supposed to match that? – So either the [] part must have at least on match, or the () part must skip the ?.

Eg. either of these would be valid: `(?:all|distinct|[(!@]?)?` (at least one match) or `(?:all|distinct|[(!@]*)` (zero or one match). I think the latter one was intended, because you can have a union statement without those extra keywords.

I'll make a quick PR with a fix.

**Comment by lstrojny** [comment] 2013-03-26 20:03
Should be fixed now. Thanks @felixbuenemann!

**Closed as completed by lstrojny** 2013-03-26 20:03 UTC
